version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3012:3012"
    volumes:
      - ./temp:/temp
      - ./logs:/logs

  sidecar:
    build:
      context: .
      dockerfile: Dockerfile.sidecar
    volumes:
      - ./temp:/temp
      - ./logs:/logs

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: arquisoft
      RABBITMQ_DEFAULT_PASS: password