version: '3.8'

services:
  document_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3004:3004"
    volumes:
      - ./temp:/temp
      - ./logs:/logs

  document_sidecar:
    build:
      context: .
      dockerfile: Dockerfile.sidecar
    volumes:
      - ./temp:/temp
      - ./logs:/logs

  document_rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: arquisoft
      RABBITMQ_DEFAULT_PASS: password